---
- name: "Apt Check"
  hosts: all
  gather_facts: true

  tasks:
    - name: debug
      debug:
        msg: "Host : {{ ansible_host }}"

    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
      when: "{{ ansible_distribution }}" == "Ubuntu" or "{{ ansible_distribution }}"" == "Debian"
