---
- hosts: all
  gather_facts: true
  tasks:
    - name: blockinfile 
      ansible.builtin.blockinfile:
        path: "{{ path }}"
        block: |
          {% for x in name_list %}
            x
          {% endfor %}
        create: yes
        mode: "0644"

    - name: echo debug for loop
      debug:
        msg: "{{ item }}"
      loop: "{{ name_list }}"



