---
- hosts: localhost
  gather_facts: true
  tasks:
    - name: Do misc command in shell
      ansible.builtin.shell: |
        python ./count.py
        exit 0
      register: rc
    - name: Show result
      ansible.bultin.debug:
        msg: "{{ rc.stdout }}"
      
