---
- hosts: all
  gather_facts: true
  tasks:
    - name: Do misc command in shell
      ansible.builtin.shell: |
        ls -la
        which python3
        pwd
        exit 0
      delegate_to: localhost
      
