---
- hosts: localhost
  gather_facts: true
  tasks:
    - name: Do misc command in shell
      ansible.builtin.shell: |
        ls -la
        which python
        pwd
        hostname
        ip a
        exit 0
      
