---
- hosts: all
  gather_facts: true
  tasks:
    - name: make group "{{user}}"
      ansible.builtin.group:
        name: "{{user}}"

    - name: make user "{{user}}" 
      ansible.builtin.user:
        name: "{{user}}"
        group: "{{user}}
        groups: 
          - sudo
        shell: "/bin/bash"

    - name: make .ssh/ folder 
      ansible.builtin.file:
        path: "/home/{{user}}/.ssh"
        state: "directory"
        mode: "0700"
        owner: "{{user}}"
        group: "{{user}}"

    - name: make authorized_keys file
      ansible.builtin.blockinfile:
        path: "/home/{{user}}/.ssh/authorized_keys"
        block: |
         {{ auth_key }}
        create: yes
        mode: "0700"
        owner: "{{user}}"
        group: "{{user}}"
