---
- hosts: all
  gather_facts: true
  tasks:
    - name: make group
      ansible.builtin.group:
        name: "{{ item.name }}"
      loop: "{{ users }}"

    - name: make user 
      ansible.builtin.user:
        name: "{{ item.name }}"
        group: "{{ item.name }}"
        groups: 
          - sudo
        shell: "/bin/bash"
        password: "{{ item.hash }}"
      loop: "{{ users }}"

    - name: make .ssh/ folder 
      ansible.builtin.file:
        path: "/home/{{ item.name }}/.ssh"
        state: "directory"
        mode: "0700"
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
      loop: "{{ users }}"

#    - name: make authorized_keys file
#      ansible.builtin.blockinfile:
#        path: "/home/{{item}}/.ssh/authorized_keys"
#        block: |
#          {% for key in auth_keys %}
#          {{ key }}
#          {% endfor %}
#        create: yes
#        mode: "0700"
#        owner: "{{item}}"
#        group: "{{item}}"
#      loop: "{{users}}"
#
#    - name: echo debug for loop
#      debug:
#        msg: "{{ item }}"
#      loop: "{{ name_list }}"



