---
- hosts: all
  gather_facts: true
  tasks:
#    - name: make group
#      ansible.builtin.group:
#        name: "{{ item.name }}"
#      with_items: "{{ users }}"
#
    - name: make user 
      ansible.builtin.user:
        name: "{{ item.name }}"
#        group: "{{ item.name }}"
#        groups: 
#          - sudo
        shell: "/bin/bash"
        password: "{{ item.hash }}"
        update_password: "always"
      with_items: "{{ users }}"

    - name: add groups 
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: 
          - sudo
      with_items: "{{ users }}"
      when: ansible_facts['os_family'] == "Debian"

    - name: add groups 
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: 
          - wheel 
      with_items: "{{ users }}"
      when: ansible_facts['os_family'] == "Archlinux"

    - name: make .ssh/ folder 
      ansible.builtin.file:
        path: "/home/{{ item.name }}/.ssh"
        state: "directory"
        mode: "0700"
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
      with_items: "{{ users }}"

    - name: make authorized_keys file
      ansible.builtin.blockinfile:
        path: "/home/{{ item.name }}/.ssh/authorized_keys"
        block: |
          {% for key in auth_keys %}
          {{ key }}
          {% endfor %}
        create: yes
        mode: "0600"
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
      with_items: "{{ users }}"

    - name: make screenrc file
      ansible.builtin.blockinfile:
        path: "/home/{{ item.name }}/.screenrc"
        block: |
          caption always "%-Lw%{= BW}%50>%n%f* %t%{-}%+Lw%<"
          escape ^t^t
          startup_message off
        create: yes
        mode: "0644"
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
      with_items: "{{ users }}"

