---
- hosts: all
  gather_facts: true
  tasks:
    - name: make group hama
      ansible.builtin.group:
        name: hama

    - name: make user hama
      ansible.builtin.user:
        name: hama
        group: hama
        groups: 
          - sudo
        authorization: ""

    - name: make .ssh/ folder 
      ansible.builtin.file:
        path: "/home/hama/.ssh"
        state: "directory"
        mode: "0700"
        owner: hama
        group: hama

    - name: make authorized_keys file
      ansible.builtin.blockinfile:
        path: "/home/hama/.ssh/authorized_keys"
        create: yes
        mode: "0700"
        owner: hama
        group: hama
        block: |
         {{ item }}
        with_items: "{{ auth_keys }}"
