---
- hosts: all
  gather_facts: true
  tasks:
    - name: make authorized_keys file change 
      ansible.builtin.lineinfile:
        path: "/home/{{ item.name }}/.ssh/authorized_keys"
        regex: "{{ item.regex }}"
        state: absent
        attributes: "check_mode"
      with_items: "{{ users }}"


