---
- hosts: localhost
  gather_facts: no 
  tasks:
    - name: CheckTime 
      set_fact:
        cur: "{{ lookup('pipe', 'TZ=JST-9 date' }}"
        cur_s: "{{ lookup('pipe', 'TZ=JST-9 date +%s' }}"
      debug:
        var:
          - cur
          - cur_s
