---
- hosts: localhost
  gather_facts: no
  vars:
    cur: "{{ lookup('pipe', 'TZ=JST-9 date') }}"
    cur_s: "{{ lookup('pipe', 'TZ=JST-9 date +%s') }}"

  tasks:
    - name: show 
      debug:
        message: "cur {{cur}}: cur_s {{cur_s}} "
